version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - '1433:1433'
    volumes:
      - ./init/sqlserver-init.sql:/docker-entrypoint-initdb.d/sqlserver-init.sql

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=YourStrong@Passw0rd
    ports:
      - '5434:5432'
    volumes:
      - ./init/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
