/*
 Navicat Premium Data Transfer

 Source Server         : LOCALHOST SQL SERVER
 Source Server Type    : SQL Server
 Source Server Version : 16004125 (16.00.4125)
 Source Host           : 127.0.0.1:1433
 Source Catalog        : AMNCLTDS0060
 Source Schema         : dbo

 Target Server Type    : SQL Server
 Target Server Version : 16004125 (16.00.4125)
 File Encoding         : 65001

 Date: 15/07/2024 10:35:11
*/


-- ----------------------------
-- Table structure for m_employee
-- ----------------------------
IF EXISTS (SELECT * FROM sys.all_objects WHERE object_id = OBJECT_ID(N'[dbo].[m_employee]') AND type IN ('U'))
	DROP TABLE [dbo].[m_employee]
GO

CREATE TABLE [dbo].[m_employee] (
  [NoRM] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [EmployeeId] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [NamaPasien] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Sebutan] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Kelamin] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [TempatLahir] date  NULL,
  [TanggalLahir] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Alamat] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [NoTelp] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [NoHP] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Darah] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [email] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [BPJSAsuransi] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [NIK] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [NamaPerusahaanAsuransi] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [EmpActiveStatus] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [TerminateDate] date  NULL,
  [MaritalStatus] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Nationality] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [EmpType] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [RosterCode] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [PosNo] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [PosTitle] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [CostCenter] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [JobLevelCode] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [JobLevel] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SEG] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SEGDescription] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [MCUMatrix] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [MedicalEntitlement] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SponsorID] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SponsorName] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SupervisorID] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SupervisorName] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [SupvCostCenter] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Company] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [ContractNumber] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [VendorId] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Vendor] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [department] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [Section] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
  [LastUpdateDate] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL
)
GO

ALTER TABLE [dbo].[m_employee] SET (LOCK_ESCALATION = TABLE)
GO


-- ----------------------------
-- Records of m_employee
-- ----------------------------
BEGIN TRANSACTION
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000021', N'MEIKY KURNIAWAN', N'MEIKY', N'M', NULL, N'7-May-1992', N'Jl. Kridasana No.74 RT020/RW009 Kel/Desa Pasiran', NULL, NULL, N'A', N'Meiky.Kurniawan@amman.co.id', NULL, N'6.17202E+15', NULL, N'Terminated', N'2021-12-31', N'Single', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'99999999', N'Supt. - Finance Analysis & Compliance', N'NULL', N'0', NULL, N'NULL', N'NULL', NULL, NULL, NULL, N'NULL', N'NULL', N'NULL', N'AMMN2011086100', N'NULL', NULL, NULL, NULL, N'FINANCE', N'FINANCE EXT REPORTING', N'12:45.8')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000022', N'CAHYANING SATYKA', N'TYKA', N'F', NULL, N'5-Jun-1993', N'Jl.Kecubung F.V No.21, RT.001,RW015 -', NULL, NULL, N'O Positive', N'CAHYANING.SATYKA@amman.co.id', NULL, N'3.27609E+15', NULL, N'Active', NULL, N'Single', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50005930', N'SUPT. - EXTERNAL REPORTING', N'AMMN1000086100', N'30', N'Superintendent', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10106694', N'IFANNA LISKA', N'AMMN2011086100', N'PT AMI', NULL, NULL, NULL, N'FINANCE', N'FINANCE EXT REPORTING', N'37:26.6')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000023', N'JONATHAN', N'JOHAN', N'M', NULL, N'31-Dec-1993', N'Jl.Krisant Blok N/23,RT003/RW012 Kel. Duri Kosambi,', NULL, NULL, NULL, N'Jonathan@amman.co.id', NULL, N'3.17301E+15', NULL, N'Active', NULL, N'Married', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50008381', N'MANAGER - FINANCE ANALYSIS & COMPLIANCE', N'AMMN1000086100', N'40', N'Manager', N'SEG0017', N'NULL', N'P-A', NULL, NULL, N'NULL', N'10106694', N'IFANNA LISKA', N'AMMN2011086100', N'PT AMI', NULL, NULL, NULL, N'FINANCE', N'FINANCE EXT REPORTING', N'42:37.3')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000024', N'MEIKY KURNIAWAN', N'MEIKY', N'M', NULL, N'7-May-1992', N'Jl. Kridasana No.74 RT020/RW009 Kel/Desa Pasiran', NULL, NULL, N'A', N'Meiky.Kurniawan@amman.co.id', NULL, N'6.17202E+15', NULL, N'Active', NULL, N'Single', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50008380', N'MANAGER - FINANCIAL REPORTING & ANALYSIS', N'AMMN1000086100', N'40', N'Manager', N'SEG0017', N'NULL', N'P-A', NULL, NULL, N'NULL', N'10106694', N'IFANNA LISKA', N'AMMN2011086100', N'PT AMI', NULL, NULL, NULL, N'FINANCE', N'FINANCE EXT REPORTING', N'42:37.2')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000025', N'RACHEL PUSPITOASRI', N'RACHEL', N'F', NULL, N'12-Aug-1984', N'JL.ARIA PUTRA 89 GREEN HILL K/11 002/004 SERUA INDAH', NULL, NULL, NULL, N'Rachel.Puspitoasri@amman.co.id', NULL, N'3.67405E+15', NULL, N'Active', NULL, N'Married', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50007343', N'SPEC. - EXTERNAL REPORTING', N'AMMN1000086100', N'5', N'Specialist', N'SEG0017', N'NULL', N'P-A', NULL, NULL, N'NULL', N'10106694', N'IFANNA LISKA', N'AMMN2011086100', N'PT AMI', NULL, NULL, NULL, N'FINANCE', N'FINANCE EXT REPORTING', N'39:46.7')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000026', N'WIDYA LESTARI', N'WIDYA', N'F', NULL, N'29-Jun-1995', N'Jl.KLP Puan TMR VII RT/RW 007/012 BLK NB-8/30 Pegangsaan Dua', NULL, NULL, N'A Positive', N'Widya.Lestari@amman.co.id', NULL, N'3.17207E+15', NULL, N'Active', NULL, N'Married', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50005934', N'SR.SPEC. - REPORTING AND FINANCING', N'AMMN1000086100', N'18', N'Sr. Specialist', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10106694', N'IFANNA LISKA', N'AMMN2011086100', N'PT AMI', NULL, NULL, NULL, N'FINANCE', N'FINANCE EXT REPORTING', N'39:46.4')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000027', N'VEMMY FEBRIANTI', N'VEMMY', N'F', NULL, N'18-Feb-1981', N'Jl.Garuda III No.E-13 Rempoa - Ciputat', NULL, NULL, NULL, N'Vemmy.Febrianti@amman.co.id', NULL, N'3.27509E+15', NULL, N'Active', NULL, N'Widowed', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50006685', N'CORPORATE SECRETARY & LEGAL', N'AMMN1000089000', N'40', N'Manager', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10106630', N'THOMAS HENGKY PRABOWO', N'AMMN2011089000', N'PT AMI', NULL, NULL, NULL, N'LEGAL', N'LEGAL', N'40:04.0')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000028', N'KARTIKA OKTAVIANA', N'VINA', N'F', NULL, N'NULL', N'Apartemen 1 Cik Ditiro, Jl. Teuku Cik Ditiro No. 1 Unit 10-I, RT 008/ RW 002', NULL, NULL, N'O Positive', N'Kartika.Octaviana@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50006693', N'VICE PRESIDENT CORPORATE COMMUNICATION & INVESTOR RELATIONS', N'AMMN1000090300', N'55', N'Regional Mgr', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10909005', N'THOMAS RAMLIE', N'AMMN2011090800', N'PT AMI', NULL, NULL, NULL, N'COMMUNICATION', N'COMMUNICATION', N'38:17.1')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10000029', N'AHMAD MUFLIH AJI', N'AJI', N'M', NULL, N'22-Jan-1998', N'Kp. Tanah 80 No. 9, 010/008 Kel/Desa Klender', NULL, NULL, N'B', N'Ahmad.Aji@amman.co.id', NULL, N'3.17507E+15', NULL, N'Active', NULL, N'Single', N'Indonesia', N'Staff', N'IDN_52_NO_T01', N'50007991', N'SR.SPEC. - REPORTING AND FINANCING', N'AMMN1000086100', N'18', N'Sr. Specialist', N'SEG0017', N'NULL', N'P-A', NULL, NULL, N'NULL', N'10106694', N'IFANNA LISKA', N'AMMN2011086100', N'PT AMI', NULL, NULL, NULL, N'FINANCE', N'FINANCE EXT REPORTING', N'31:09.9')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100061', N'LALU WAHYUNADI', N'WAHYU', N'M', NULL, N'18-Jan-1970', N'Jalan Pantai Sire no. 39 BTN 004/100 Pagutan Barat Mataram', N'81803669861', NULL, NULL, N'Wahyunadi@amman.co.id', NULL, N'5.27102E+15', NULL, N'Terminated', N'2022-02-28', N'Married', N'Indonesia', N'Staff', N'IDN_52_NO_T05', N'99999999', N'Planning, Scheduling & Reporting Officer', N'NULL', N'0', NULL, N'NULL', N'NULL', NULL, NULL, NULL, N'NULL', N'NULL', N'NULL', N'AMMN4041083000', N'NULL', NULL, NULL, NULL, N'TRANSPORTATION', N'TRANSPORT', N'16:47.0')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100071', N'SAPI''I', N'SAPI''I', N'M', NULL, N'15-Jul-1971', N'Ling Sampir 010/004 Sampir Taliwang', N'81238255571', N'6.28E+11', NULL, N'Sapii@amman.co.id', NULL, N'5.20702E+15', NULL, N'Active', NULL, N'Married', N'Indonesia', N'Staff', N'IDN_42_ST_T38', N'50000378', N'SUPV. - CORE SHED', N'AMMN2011020100', N'10', N'Foreman/Supv', N'SEG0016', N'Coreshed', N'P-N', NULL, NULL, N'NULL', N'10105912', N'JAN SASTRAJAYA', N'AMMN2011020100', N'PT AMNT', NULL, NULL, NULL, N'MINE TECH. SERVICES', N'MINE GEOLOGY', N'31:47.3')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100082', N'MAHDI', N'MAHDI', N'M', NULL, N'1-Sep-1972', N'DSN. TATAR 005/003 BENETE MALUK', N'81237974578', NULL, NULL, N'Mahdi@amman.co.id', NULL, N'5.20708E+15', NULL, N'Active', NULL, N'Married', N'Indonesia', N'Staff', N'IDN_42_ST_T27', N'50000388', N'ENGINEER - GEOTECH SUPPORT', N'AMMN2011020100', N'10', N'Foreman/Supv', N'SEG0020', N'Mine Geology Field', N'P-B', NULL, NULL, N'NULL', N'10106395', N'FAISAL MIRZA', N'AMMN2011020100', N'PT AMNT', NULL, NULL, NULL, N'MINE TECH. SERVICES', N'MINE GEOTECHNICAL', N'41:27.6')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100115', N'KHAIRUL ANWAR', N'ERUL', N'M', NULL, N'6-Jun-1971', N'JL.A.SUCIPTO GRIYA ELEN BLOK B-6 008/021 PEJERUK AMPENAN', N'81353656003', NULL, NULL, N'Khairul.Anwar@amman.co.id', NULL, N'5.27101E+15', NULL, N'Terminated', N'2021-02-28', N'Married', N'Indonesia', N'Staff', N'IDN_52_D7_T16', N'99999999', N'Geologist - Modelling', N'NULL', N'0', NULL, N'NULL', N'NULL', NULL, NULL, NULL, N'NULL', N'NULL', N'NULL', N'AMMN2011020100', N'NULL', NULL, NULL, NULL, N'MINE TECH. SERVICES', N'MINE GEOLOGY', N'07:12.7')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100119', N'ABDUL HAMID MS.', N'HAMID', N'M', NULL, N'7-Feb-1968', N'JL PENDIDIKAN NO. 42 001/001 MALUK MALUK', N'82340774012', NULL, NULL, N'Abdul.Hamid@amman.co.id', NULL, N'5.20708E+15', NULL, N'Terminated', N'2023-02-28', N'Married', N'Indonesia', N'Non Staff', N'IDN_42_SH_T12', N'99999999', N'Warehouseman', N'NULL', N'0', NULL, N'NULL', N'NULL', NULL, NULL, NULL, N'NULL', N'NULL', N'NULL', N'AMMN4041084300', N'NULL', NULL, NULL, NULL, N'SCM ASSET', N'ASSET WAREHOUSE', N'31:00.9')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100135', N'LALU ZARKASI', N'ZARKASI', N'M', NULL, N'31-Dec-1975', N'DSN MUHAJIRIN 005/002 BUKIT DAMAI MALUK', N'82247188157', NULL, NULL, N'Lalu.Zarkasi@amman.co.id', NULL, N'5.20708E+15', NULL, N'Active', NULL, N'Married', N'Indonesia', N'Staff', N'IDN_42_ST_T41', N'50000389', N'ENGINEER - GEOTECH SUPPORT', N'AMMN2011020100', N'10', N'Foreman/Supv', N'SEG0020', N'Mine Geology Field', N'P-B', NULL, NULL, N'NULL', N'10106395', N'FAISAL MIRZA', N'AMMN2011020100', N'PT AMNT', NULL, NULL, NULL, N'MINE TECH. SERVICES', N'MINE GEOTECHNICAL', N'41:27.6')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100617', N'ANTHONY SIMMONDS', N'TONY', N'M', NULL, N'NULL', N'Lr. Kelicing 239, Townsite, Batu Hijau -', NULL, N'6.28E+11', NULL, N'Anthony.Simmonds@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'Australia', N'Expat', N'IDN_52_NO_T01', N'50000680', N'GENERAL MANAGER PROCESS & FIXED PLANT', N'AMMN2011030000', N'55', N'Regional Mgr', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10101631', N'WUDI RAHARJO', N'AMMN2011080000', N'PT AMNT', NULL, NULL, NULL, N'PROCESS MANAGEMENT', N'PROCESS ADMIN', N'30:56.7')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100620', N'SHARAD YADAV', N'SHARAD', N'M', NULL, N'20-Oct-1976', N'Apartemen Kusuma Chandra Tower III Unit 17M SCBD Lot.20,Jl.Jend.Sudirman Kav52-53', NULL, N'6.28E+11', NULL, N'Sharad.Yadav@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'India', N'Expat', N'IDN_52_NO_T01', N'50000336', N'VICE PRESIDENT MARKETING', N'AMMN2011091000', N'50', N'Senior Manager', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10909004', N'NAVEEN CHANDRALAL', N'AMMN2011090800', N'PT AMNT', NULL, NULL, NULL, N'MARKETING', N'MARKETING', N'43:12.9')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100621', N'STUART JAMES ASHDOWN', N'STUART', N'M', NULL, N'17-Jul-1973', N'Lr. Din 148, Townsite, Batu Hijau -', NULL, NULL, NULL, N'Stuart.Ashdown@amman.co.id', NULL, NULL, NULL, N'Terminated', N'2021-04-29', N'Married', N'Australia', N'Staff', N'IDN_52_NO_T01', N'99999999', N'Sr.Manager Mine Technical Services', N'NULL', N'0', NULL, N'NULL', N'NULL', NULL, NULL, NULL, N'NULL', N'NULL', N'NULL', N'AMMN2011090800', N'NULL', NULL, NULL, NULL, N'MANAGEMENT', N'MANAGEMENT', N'07:12.9')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100626', N'MICHAEL JOHN SERVOS', N'MIKE', N'M', NULL, N'13-Apr-1959', N'Lr. Jamrud 202, Townsite, Batu Hijau -', NULL, N'6.28E+11', NULL, N'Michael.Servos@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'Australia', N'Expat', N'IDN_52_NO_T01', N'50000023', N'SR. MANAGER - DRILL & BLAST', N'AMMN2011020000', N'50', N'Senior Manager', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10100637', N'WAYNE PERRY', N'AMMN2011090800', N'PT AMNT', NULL, NULL, NULL, N'MINE SUPPORT', N'MINE SUPPORT', N'45:47.6')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100628', N'CHEE TAN', N'CHEE', N'M', NULL, N'NULL', N'The Pakubuwono Spring, Unit Cherrywood 51B Jl. Teuku Nyak Arief No. 9 Rt6 Rw2', NULL, N'6.28E+11', NULL, N'Chee.Tan@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Single', N'Australia', N'Expat', N'IDN_52_NO_T05', N'50000793', N'GENERAL MANAGER PROJECT DEVELOPMENT & IFMS', N'AMMN2011088800', N'60', N'General Manager', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10101631', N'WUDI RAHARJO', N'AMMN2011080000', N'PT AMNT', NULL, NULL, NULL, N'PROJECT DEVELOPMENT', N'PROJECT DEVELOPMENT ADMIN', N'44:03.5')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100629', N'ROHIT PRASAD', N'ROHIT', N'M', NULL, N'10-Jul-1973', N'The Royal Springhill Residence Tower Lavender Unit 32M Jl. Benyamin Suaeb Blok D7', NULL, NULL, NULL, N'Rohit.Prasad@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'India', N'Expat', N'IDN_52_NO_T01', N'50001060', N'SR. MANAGER - ADVISOR - SCM', N'AMMN2011084000', N'50', N'Senior Manager', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10909007', N'ADITYA SASMITO', N'AMMN2011090800', N'PT AMNT', NULL, NULL, NULL, N'SCM PROCUREMENT BULK', N'PROCUREMENT BULK', N'30:49.3')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100633', N'JAMES ADAMS', N'JAMES', N'M', NULL, N'8-Apr-1976', N'Lr. Angsoka 538, Townsite, Batu Hijau -', N'61413298939', N'6.28E+11', NULL, N'James.Adams@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'Australia', N'Expat', N'IDN_63_ST_T20', N'50001061', N'SR. MANAGER - CAPITAL PROCUREMENT & SERVICES', N'AMMN2011991000', N'50', N'Senior Manager', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10909007', N'ADITYA SASMITO', N'AMMN2011090800', N'PT AMNT', NULL, NULL, NULL, N'SCM PROCUREMENT NON MINE', N'PROCUREMENT NON MINING ADMIN', N'31:21.3')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100634', N'PERCY FREDY CONDORI CRUZ', N'PERCY', N'M', NULL, N'28-Sep-1971', N'Lr. Galumpang 163, Townsite, Batu Hijau -', N'926501226', N'6.28E+11', NULL, N'Percy.Condori@amman.co.id', NULL, NULL, NULL, N'Terminated', N'2024-03-27', N'Married', N'Peru', N'Expat', N'IDN_52_NO_T01', N'99999999', N'Manager - Metallurgy', N'NULL', N'0', NULL, N'NULL', N'NULL', NULL, NULL, NULL, N'NULL', N'NULL', N'NULL', N'AMMN2011054100', N'NULL', NULL, NULL, NULL, N'PROCESS MANAGEMENT', N'PROCESS ADMIN', N'31:44.3')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100636', N'ROBERT ANDREW MALSEED', N'ROBBIE', N'M', NULL, N'16-Sep-1975', N'Lr. Binong Kecil 199, Townsite, Batu Hijau -', NULL, NULL, NULL, N'Robert.Malseed@amman.co.id', NULL, NULL, NULL, N'Terminated', N'2021-06-11', N'Married', N'Australia', N'Expat', N'IDN_52_NO_T01', N'99999999', N'Sr.Spec. - Internal Multimedia&Vid Prod', N'NULL', N'0', NULL, N'NULL', N'NULL', NULL, NULL, NULL, N'NULL', N'NULL', N'NULL', N'AMMN2011090800', N'NULL', NULL, NULL, NULL, N'MANAGEMENT', N'MANAGEMENT', N'07:27.7')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100637', N'WAYNE PERRY', N'WAYNE', N'M', NULL, N'NULL', N'Lr. Din 142, Townsite, Batu Hijau -', NULL, N'6.28E+11', NULL, N'Wayne.Perry@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'Australia', N'Expat', N'IDN_52_NO_T05', N'50000355', N'GENERAL MANAGER MINING', N'AMMN2011090800', N'55', N'Regional Mgr', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10101631', N'WUDI RAHARJO', N'AMMN2011080000', N'PT AMNT', NULL, NULL, NULL, N'MANAGEMENT', N'MANAGEMENT', N'30:40.0')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100639', N'CHANDRASEKAR KRISHNAMURTHI', N'CHANDRASEKAR', N'M', NULL, N'NULL', N'Apartemen Taman Rasuna Tower 17 FL 23 Unit 23G Jl. HR Rasuna Said Rt. 16 Rw. 1', NULL, N'6.28E+11', NULL, N'Chandrasekar.Krishnamurthi@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'India', N'Expat', N'IDN_52_NO_T01', N'50000358', N'CHIEF FINANCIAL OFFICER', N'AMMN2011086100', N'65', N'Director', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10909004', N'NAVEEN CHANDRALAL', N'AMMN2011090800', N'PT AMNT', NULL, NULL, NULL, N'FINANCE', N'FINANCE ADMIN', N'41:13.7')
GO

INSERT INTO [dbo].[m_employee] ([NoRM], [EmployeeId], [NamaPasien], [Sebutan], [Kelamin], [TempatLahir], [TanggalLahir], [Alamat], [NoTelp], [NoHP], [Darah], [email], [BPJSAsuransi], [NIK], [NamaPerusahaanAsuransi], [EmpActiveStatus], [TerminateDate], [MaritalStatus], [Nationality], [EmpType], [RosterCode], [PosNo], [PosTitle], [CostCenter], [JobLevelCode], [JobLevel], [SEG], [SEGDescription], [MCUMatrix], [MedicalEntitlement], [SponsorID], [SponsorName], [SupervisorID], [SupervisorName], [SupvCostCenter], [Company], [ContractNumber], [VendorId], [Vendor], [department], [Section], [LastUpdateDate]) VALUES (NULL, N'10100640', N'PIETER ANDRIES KOTZEE', N'PIETER', N'M', NULL, N'15-Jun-1978', N'Jl. Raya Ketimus 214, Townsite, Batu Hijau -', NULL, N'6.28E+11', NULL, N'Pieter.Kotzee@amman.co.id', NULL, NULL, NULL, N'Active', NULL, N'Married', N'Australia', N'Expat', N'IDN_52_NO_T01', N'50000359', N'SR. ADVISOR COMMERCIAL', N'AMMN2011020000', N'45', N'Coord. Manager', N'SEG0017', N'Worker', N'P-A', NULL, NULL, N'NULL', N'10100637', N'WAYNE PERRY', N'AMMN2011090800', N'PT AMNT', NULL, NULL, NULL, N'COMMERCIAL', N'COMMERCIAL', N'31:33.0')
GO

COMMIT TRANSACTION
GO
